### ISSUE TITLE
Hello friend

### ISSUE THREAD

**Issue by V3lasca** [ElliotAlderson51/Fsociety#1]
Hello, my name is V3lasc.

I wanted to say that I'm a fan of "Mr.Robot" as well. I've enjoyed watching the series.
Just checked out your website, and it was cool.
If you need help with you website, I would not mind helping out. I know some HTML and CSS.

Take care

**Comment by ElliotAlderson51** [comment]
Hey V3lasc,

I'm going back to the military.. so I'll not have time to make the website looks better.. or to get help..
thank you for asking (:

**Comment by V3lasca** [comment]
No problem dude. Whenever you do have the time just text me back, and I will gladly help out.
